netsage-project/netsage-pipeline

bin/json2lines
bin/lines2json
bin/netsage-flow-archive-daemon
bin/netsage-raw-data-importer
conf/config.xml.example
conf/logrotate.d/netsage_raw_data_importer
conf/netsage_deidentifier.xml.example
conf/netsage_finished_flow_mover.xml.example
conf/netsage_flow_archive.xml.example
conf/netsage_flow_cache.xml.example
conf/netsage_flow_stitcher.xml.example
conf/netsage_netflow_importer.xml.example
conf/netsage_raw_data_importer.xml.example
conf/netsage_tagger.xml.example
init.d/netsage-flow-archive-daemon
lib/GRNOC/NetSage/Deidentifier/FlowArchive.pm
lib/GRNOC/NetSage/Deidentifier/FlowTagger.pm
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm
lib/GRNOC/NetSage/Deidentifier/Pipeline.pm
lib/GRNOC/NetSage/Deidentifier/RawDataImporter.pm

Adding sensor id/type, raw data importer, Rabbit "durable" flag, update example config files, etc.

Sensor id type

---

INSTALL.md
conf/netsage_deidentifier.xml.example
conf/netsage_finished_flow_mover.xml.example
conf/netsage_flow_archive.xml.example
conf/netsage_flow_cache.xml.example
conf/netsage_flow_stitcher.xml.example
conf/netsage_netflow_importer.xml.example
conf/netsage_raw_data_importer.xml.example
conf/netsage_tagger.xml.example
grnoc-netsage-deidentifier.spec
init.d/netsage-deidentifier-daemon
init.d/netsage-flow-cache-daemon
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm

Add CentOS 7 support and update default config files with better Rabbit defaults. Also change nfdump command to use the "-a" flag to aggregate based on 5 tuple

Centos7 support

---

conf/netsage_netflow_importer.xml.example
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm

Add "sflow" flow type flag (still defaults to "netflow")

Add "sflow" flow type flag

---

CHANGES.md
grnoc-netsage-deidentifier.spec
lib/GRNOC/NetSage/Deidentifier.pm

Tagging for 0.0.8 to release the min threshold feature

preparing to tag 0.0.8

---

lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm

Using Try::Tiny with File::Find::Rule

Using Try::Tiny with File::Find::Rule

---

bin/netsage-flow-stitcher-daemon
conf/netsage_flow_cache.xml.example
conf/netsage_flow_stitcher.xml.example
conf/netsage_netflow_importer.xml.example
lib/GRNOC/NetSage/Deidentifier/FlowCache.pm
lib/GRNOC/NetSage/Deidentifier/FlowStitcher.pm
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm

Make IPC key configurable

---

CHANGES.md
conf/netsage_netflow_importer.xml.example
grnoc-netsage-deidentifier.spec
lib/GRNOC/NetSage/Deidentifier.pm
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm

Remove buggy File::Find::Rule module
Prepare for 0.1.0 release

File find fixes

---

.gitignore
CHANGES.md
bin/netsage-finished-flow-mover-daemon
conf/systemd/netsage-deidentifier.service
conf/systemd/netsage-finished-flow-mover.service
conf/systemd/netsage-flow-archive.service
conf/systemd/netsage-flow-cache.service
conf/systemd/netsage-flow-stitcher.service
conf/systemd/netsage-netflow-importer.service
conf/systemd/netsage-tagger.service
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm
lib/GRNOC/NetSage/Deidentifier/Pipeline.pm

Change start order of init scripts; add systemd unit files for CentOS 7

Improvements to startup scripts

---

docker-compose.yml

This contains James Deaton's UDP fix. Makes sense and seems to work in my testing.

Docker collector UDP fix

---

compose/netsage_shared.xml
docker-compose.build.yml
docker-compose.yml
env.example
lib/GRNOC/NetSage/Deidentifier/NetflowImporter.pm

Updating SensorName to be populated from env if xml value is set to start with a $sign

Dockerize sensorName

---

docs/deploy/docker_install.md

adding documentation related to the Advanced flow pipeline.

[TechDebt] Updating the documentation for multiple collectors

---

compose/importer/Dockerfile
compose/importer/docker_init.sh
compose/logstash/Dockerfile
docker-compose.yml

Note: CSV file has issues, so this should work, once data is fixed or logstash configs

Fixing broken build

---

website/docs/deploy/bare_metal_install.md
website/docs/deploy/choosing.md
website/docusaurus.config.js

Renaming a few titles
ChangeLog:
- Renames a few heading
- Fix Edit URL

Rename a few titles

---

website/versioned_docs/version-1.2.6/pipeline_logstash.md

updated docs for 1.2.6 retroactively

Updated v1.2.6 doc listing logstash configs

---

conf-logstash/40-aggregation.conf
env.example
website/docs/components/docker_env.md

ChangeLog:
- Added two new env variables.
- exposed logstash cache to local data volume
- Added documentation

[TechDebt][Bug] Added timeout and inactivity timeout env.

---

website/docs/pipeline/importer.md
website/docs/pipeline/intro.md
website/docs/pipeline/logstash.md
website/docs/pipeline/nfdump.md
website/docs/pipeline/tstat.md

- updates to navigation.
- added tstat/nfdump sections
- more troubleshooting updates

Documentation updates

---

CHANGES.md
bin/restart-logstash.sh
cron.d/netsage-logstash-restart.cron
grnoc-netsage-deidentifier.spec
lib/GRNOC/NetSage/Deidentifier.pm
website/docs/components/docker_env.md
website/docs/components/docker_upgrade.md
website/docs/deploy/docker_install_advanced.md
website/docs/deploy/docker_install_simple.md

Updates to version no., changes file, documentation.

V1.2.7 prep

---

.gitignore
compose/importer/Dockerfile
compose/logstash/Dockerfile
grnoc-netsage-deidentifier.spec

Upgrading Logstash in containers to: 7.10.1

logstash upgrade

---

conf-logstash/15-sensor-specific-changes.conf
conf-logstash/20-add-id.conf
conf-logstash/90-additional-fields.conf
conf-logstash/95-cleanup.conf
conf-logstash/ruby/domestic.rb

Added renaming of NEAAR sensor based on ifindex; will now keep ifindex fields
For country_scope, added consideration of continents when countries are missing

1.2.8changes

---

website/docs/components/docker_upgrade.md

Made some minor adjustments based on our experience earlier and discussion. I'm not certain of your convention for referencing local install directories - probably now that I think about it, it could be in the narrative and not the code block.

Minor updates to upgrade documentation

---

docker-compose.override_example.yml

Switching collectors to use the nightly alpine release to pickup required patch

nfdump patch
